hahat

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -17,31 +17,52 @@ jobs:
         uses: tim-actions/get-pr-commits@master
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-      - name: Check Commit Type
+
+      - name: Check subsystem
         uses: tim-actions/commit-message-checker-with-regex@master
         with:
           commits: ${{ steps.get-pr-commits.outputs.commits }}
-          pattern: '\[[^]]+\] .+$'
+          pattern: '^[\h]*([^:\h]+)[\h]*:'
           flags: 'gm'
-          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
-      - name: Check Line Length
+          error: 'Failed to find subsystem in subject'
+          post_error: |+
+            See the document below for help on formatting commits for the project.
+
+            https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
+
+      - name: Check Subject Line Length
         if: ${{ success() || failure() }}
         uses: tim-actions/commit-message-checker-with-regex@master
         with:
           commits: ${{ steps.get-pr-commits.outputs.commits }}
-          pattern: '^[^#].{74}'
-          error: 'The maximum line length of 74 characters is exceeded.'
+          pattern: '^.{0,75}(\n.*)*$'
+          error: 'Subject too long (max 75)'
+          post_error: |+
+            See the document below for help on formatting commits for the project.
+
+            https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
+
+      - name: Check Body Line Length
+        if: ${{ success() || failure() }}
+        uses: tim-actions/commit-message-checker-with-regex@master
+        with:
+          commits: ${{ steps.get-pr-commits.outputs.commits }}
+          pattern: '^.+(\n.{0,72})*$'
+          error: 'Body line too long (max 72)'
+          post_error: |+
+            See the document below for help on formatting commits for the project.
+
+            https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
+
       - name: Check for Resolves / Fixes
         if: ${{ success() || failure() }}
         uses: tim-actions/commit-message-checker-with-regex@master
         with:
           commits: ${{ steps.get-pr-commits.outputs.commits }}
-          pattern: '\\s*Fixes\\s*:?\\s*(#\\d+|github\.com\/kata-containers\/[a-z-.]*#\\d+)'
+          pattern: '\s*Fixes\s*:?\s*(#\d+|github\.com\/kata-containers\/[a-z-.]*#\d+)'
           error: 'No "Fixes" found'
+          post_error: |+
+            See the document below for help on formatting commits for the project.
 
-      - name: Error Tips
-        if: ${{ failure() }}
-        # run: echo "::debug::checkcommits failed. See the document below for help on formatting\ncommits for the project.\n\nhttps://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format"
-        run: echo '::set-env name=SELECTED_COLOR::green'
-      - name: Get color
-        run: echo 'The selected color is' $SELECTED_COLOR
+            https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
+
